### PR TITLE
Colored name avatars

### PR DESCRIPTION
**Pull request by boukestam**
Hi guys, I added colored name avatars and fixed an issue with the reminder subject not being hidden when its just 'reminder'

image

I didn't want to just push to master so you can look at my code and give some feedback. I'll merge if there are no problems

### CODE REVIEW

**Comment by russelldc** [comment]
I don't see the colored name icons at all.

And this error is showing:

`Uncaught TypeError: Cannot set property 'innerHTML' of null`

at line:

```
email.querySelector(".WA.xY").innerHTML = "<div class='" + AVATAR_CLASS + "' style='background: #" + nameColors[first - 65] + "'>" + name[0] + "</div>";
```

**Comment by russelldc** [comment]
In the screenshot, it looks like you've added them to the right of the checkbox. I think it'd be best if they replaced the checkbox, except on hover or checked.

Also, the font-weight on the text in the avatar names should be lighter, 300 looks most similar to the original Inbox for me.

**Comment by russelldc** [comment]
Related to my last comment, this css was shared by someone using the Sender Icons extension:

```
/* Sender Icons */
.yX.xY div:nth-child(n+3) {
    position: absolute;
    margin-left: -58px;
    z-index: -1;
    display: inline;
}
```

You could probably do something similar. The z-index value would make it appear below the checkmark when that becomes un-hidden.

**Comment by russelldc** [comment]
To fix the positioning, I did this locally (but this doesn't work properly to show/hide checkbox):

I changed the class/element it was trying to attach to: 'email.querySelector(".zA > .aid").innerHTML = ...`

Then I changed the left position and font-weight (more similar to original Inbox): `left: -11px; font-weight: 300`

**Comment by russelldc** [comment]
This worked for me locally:

```javascript
if (first >= 65 && first <= 90) { // between A and Z
	const targetElement = email.querySelector(".aid");

	if (targetElement.getElementsByClassName(AVATAR_CLASS).length == 0) {
		const avatarElement = document.createElement("div");
		avatarElement.className = AVATAR_CLASS;
		avatarElement.style.background = "#" + nameColors[first - 65];
		avatarElement.innerText = name[0];
		targetElement.appendChild(avatarElement);
	}

	email.classList.add(AVATAR_EMAIL_CLASS);
}
```

plus this css:
```css
/* Name avatar */
.avatar {
  color: #fff;
  border-radius: 50%;
  font-weight: 300;
  position: relative;
  left: -10px;
  flex: 32px 0 0;
  width: 32px;
  height: 32px;
  text-align: center;
  line-height: 32px;
}

.email-with-avatar:hover .avatar {
  display: none;
}

.email-with-avatar > .aid > div[aria-checked="true"] + .avatar {
  display: none;
}
```

This replaces the checkbox with the avatar name, and hides it to show the checkbox on hover. It will also hide the avatar name/icon when the checkbox is checked.

**Comment by russelldc** [comment]
Screen Shot 2019-04-09 at 5 49 05 PM

**Comment by russelldc** [comment]
Screen Shot 2019-04-09 at 6 14 37 PM

**Comment by boukestam** [comment]
This is weird, there seems to be a difference between our html structures. I get an error with your code: 

script.js:226 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at updateReminders (script.js:226)

The html of an email at my end looks like this 
```html
<tr class="zA yO" jsaction="bjyjJe:NOSeAe;pInidd:NOSeAe;" jscontroller="ZdOxDb" jsmodel="nXDxbd" id=":9v" tabindex="-1" aria-labelledby=":9w" draggable="true">
   <td class="PF xY"></td>
   <td id=":9x" class="oZ-x3 xY" style="">
      <div id=":9y" class="oZ-jc T-Jo J-J5-Ji " role="checkbox" aria-labelledby=":9w" dir="ltr" aria-checked="false" tabindex="-1">
         <div class="T-Jo-auh"></div>
      </div>
   </td>
   <td class="apU xY"><span id=":9z" class="aXw T-KT" title="Not starred" aria-label="Not starred" role="button"><img class="T-KT-JX" src="images/cleardot.gif" alt="Not starred"></span></td>
   <td class="WA xY" jsaction="crxiQe" jscontroller="v9XiUc">
      <div class="pG" data-tooltip-contained="true" data-tooltip-align="b,l" data-tooltip-delay="1500" aria-label="Important mainly because you often read messages with this label." role="img" id=":a0">
         <div class="T-ays-a45">Important mainly because you often read messages with this label.<br><span class="aol">Click to teach Gmail this conversation is not important.</span></div>
         <div class="pH a9q"></div>
         <div class="bnj "></div>
      </div>
   </td>
   <td class="yX xY ">
      <div id=":9w" class="afn"><span class="bA4"><span class="yP" email="notifications@github.com" name="Anran" data-hovercard-id="notifications@github.com">Anran</span></span> <span class="bx0">3</span>,<span data-thread-id="#thread-f:1630348820378998988" data-legacy-thread-id="16a0299d3aaad8cc" data-legacy-last-message-id="16a02b8df986daff" data-legacy-last-non-draft-message-id="16a02b8df986daff">[boukestam/inbox-in-gmail] Available to firefox (#24)</span>, <span>9:59 AM</span>, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute.</div>
      <div id=":a1" class="yW"><span class="bA4"><span class="yP" email="notifications@github.com" name="Anran" data-hovercard-id="notifications@github.com" data-hovercard-owner-id="23">Anran</span></span> <span class="bx0">3</span></div>
   </td>
   <td id=":a2" tabindex="-1" class="xY a4W">
      <div class="a4X" style="padding-right:17ex;">
         <div class="xS" role="link">
            <div class="xT">
               <div class="y6"><span id=":a4" class="bog"><span data-thread-id="#thread-f:1630348820378998988" data-legacy-thread-id="16a0299d3aaad8cc" data-legacy-last-message-id="16a02b8df986daff" data-legacy-last-non-draft-message-id="16a02b8df986daff">[boukestam/inbox-in-gmail] Available to firefox (#24)</span></span></div>
               <span class="y2"><span class="Zt">&nbsp;-&nbsp;</span>https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute</span>
            </div>
         </div>
         <span class="aKS">
            <div class="T-I J-J5-Ji aOd aS9 T-I-awv L3" role="button" tabindex="0"><span class="aJ6">View Issue</span><img class="J-J5-Ji aTn aJ4" src="images/cleardot.gif" alt=""></div>
         </span>
      </div>
   </td>
   <td class="byZ xY"></td>
   <td class="yf xY ">&nbsp;</td>
   <td class="xW xY "><span title="Wed, Apr 10, 2019, 9:59 AM" id=":a5" aria-label="Wed, Apr 10, 2019, 9:59 AM"><span>9:59 AM</span></span></td>
   <td class="bq4 xY">
      <ul class="bqY" id=":a6" role="toolbar">
         <li class="bqX brq pW" data-tooltip="Archive"></li>
         <li class="bqX bru" data-tooltip="Delete" jsaction="zM6fo" jscontroller="pmCKac"></li>
         <li class="bqX brs" data-tooltip="Mark as unread" jsaction="XdlY1e" jscontroller="VtSflc"></li>
         <li class="bqX brv" data-tooltip="Snooze" jsaction="u4Fnue" jscontroller="PKSrle"></li>
      </ul>
   </td>
</tr>
```

**Comment by russelldc** [comment]
@boukestam Ugh, that sucks. I was hoping we could get this merged :P

To make sure we're aware of all variables... do you use the Default inbox type, or otherwise? Does your code work for you in every folder? The code I pasted above works for me in every folder.

I also have the Important indicator turned off.

**Comment by russelldc** [comment]
Here's what my email HTML looks like with the extension turned off:

```html
<tr class="zA yO btb  byw" jsaction="bjyjJe:NOSeAe;pInidd:NOSeAe;" jscontroller="ZdOxDb" jsmodel="nXDxbd" id=":24" tabindex="0" aria-labelledby=":25" draggable="true">
  <td class="PF xY PE"></td>
  <td id=":26" class="oZ-x3 xY aid" style="">
    <div id=":27" class="oZ-jc T-Jo J-J5-Ji " role="checkbox" aria-labelledby=":25" dir="ltr" aria-checked="false" tabindex="-1">
      <div class="T-Jo-auh"></div>
    </div>
  </td>
  <td class="apU xY"><span id=":28" class="aXw T-KT" title="Not starred" aria-label="Not starred" role="button"><img class="T-KT-JX" src="images/cleardot.gif" alt="Not starred"></span></td>
  <td class="xY bnk byv"></td>
  <td class="yX xY ">
    <div id=":25" class="afn">Joey, Bouke, me 7,Side Bar?, has attachment, Apr 8, I tried mucking with it but didn't have much luck it keeps adding to the width when it's opened an closed. Also because the compose icon is in a position: fixed I was having a more difficult.</div>
    <div id=":29" class="yW"><span class="bA4"><span class="yP" email="joey@joeytroy.com" name="Joey" data-hovercard-id="joey@joeytroy.com">Joey</span><span class="yP">, </span><span class="yP" email="bouke.stam@gmail.com" name="Bouke" data-hovercard-id="bouke.stam@gmail.com">Bouke</span><span class="yP">, </span><span class="yP" email="danielcrussell@gmail.com" name="me" data-hovercard-id="danielcrussell@gmail.com">me</span></span> <span class="bx0">7</span></div>
  </td>
  <td id=":2a" tabindex="-1" class="xY a4W">
    <div class="xS" role="link">
      <div class="xT">
        <div class="y6"><span id=":2c" class="bog"><span data-thread-id="#thread-f:1630262700608949704" data-legacy-thread-id="169fdb49e85d8dc8" data-legacy-last-message-id="169fdd5caf34a5d7" data-legacy-last-non-draft-message-id="169fdd5caf34a5d7">Side Bar?</span></span></div>
        <span class="y2"><span class="Zt">&nbsp;-&nbsp;</span>I tried mucking with it but didn't have much luck it keeps adding to the width when it's opened an closed. Also because the compose icon is in a position: fixed I was having a more difficult</span>
      </div>
    </div>
    <div class="brd" role="list" jscontroller="tnECjd">
      <span class="bzB"> Attachments</span>
      <div class="brc" data-index="0" tabindex="0" title="image.png" role="listitem" jsaction="lkS8Jd"><img class="brf" aria-hidden="true" src="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x16.png" srcset="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x32.png 2x"><span class="brg">image.png</span></div>
      <div class="brc" data-index="1" tabindex="0" title="image.png" role="listitem" jsaction="lkS8Jd"><img class="brf" aria-hidden="true" src="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x16.png" srcset="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x32.png 2x"><span class="brg">image.png</span></div>
    </div>
  </td>
  <td class="byZ xY"></td>
  <td class="yf xY "><img class="yE" src="images/cleardot.gif" title="Has attachment" alt="Has attachment"></td>
  <td class="xW xY "><span title="Mon, Apr 8, 2019, 5:44 PM" id=":2d" aria-label="Mon, Apr 8, 2019, 5:44 PM"><span>Apr 8</span></span></td>
  <td class="bq4 xY">
    <ul class="bqY" id=":2e" role="toolbar">
      <li class="bqX brq" data-tooltip="Archive" jsaction="JqEhuc" jscontroller="pk1i4d"></li>
      <li class="bqX bru" data-tooltip="Delete" jsaction="zM6fo" jscontroller="pmCKac"></li>
      <li class="bqX brs" data-tooltip="Mark as unread" jsaction="XdlY1e" jscontroller="VtSflc"></li>
      <li class="bqX brv" data-tooltip="Snooze" jsaction="u4Fnue" jscontroller="PKSrle"></li>
    </ul>
  </td>
</tr>
```

Here's what my email HTML looks like with the extension (with modified code above) active:

```html
<tr class="zA yO btb byw email-with-avatar" jsaction="bjyjJe:NOSeAe;pInidd:NOSeAe;" jscontroller="ZdOxDb" jsmodel="nXDxbd" id=":24" tabindex="0" aria-labelledby=":25" draggable="true">
  <td class="PF xY PE"></td>
  <td id=":26" class="oZ-x3 xY aid" style="">
    <div id=":27" class="oZ-jc T-Jo J-J5-Ji " role="checkbox" aria-labelledby=":25" dir="ltr" aria-checked="false" tabindex="-1">
      <div class="T-Jo-auh"></div>
    </div>
    <div class="avatar" style="background: rgb(41, 127, 184);">J</div>
  </td>
  <td class="apU xY"><span id=":28" class="aXw T-KT" title="Not starred" aria-label="Not starred" role="button"><img class="T-KT-JX" src="images/cleardot.gif" alt="Not starred"></span></td>
  <td class="xY bnk byv"></td>
  <td class="yX xY ">
    <div id=":25" class="afn">Joey, Bouke, me 7,Side Bar?, has attachment, Apr 8, I tried mucking with it but didn't have much luck it keeps adding to the width when it's opened an closed. Also because the compose icon is in a position: fixed.</div>
    <div id=":29" class="yW"><span class="bA4"><span class="yP" email="joey@joeytroy.com" name="Joey" data-hovercard-id="joey@joeytroy.com">Joey</span><span class="yP">, </span><span class="yP" email="bouke.stam@gmail.com" name="Bouke" data-hovercard-id="bouke.stam@gmail.com">Bouke</span><span class="yP">, </span><span class="yP" email="danielcrussell@gmail.com" name="me" data-hovercard-id="danielcrussell@gmail.com">me</span></span> <span class="bx0">7</span></div>
  </td>
  <td id=":2a" tabindex="-1" class="xY a4W">
    <div class="xS" role="link">
      <div class="xT">
        <div class="y6"><span id=":2c" class="bog"><span data-thread-id="#thread-f:1630262700608949704" data-legacy-thread-id="169fdb49e85d8dc8" data-legacy-last-message-id="169fdd5caf34a5d7" data-legacy-last-non-draft-message-id="169fdd5caf34a5d7">Side Bar?</span></span></div>
        <span class="y2"><span class="Zt">&nbsp;-&nbsp;</span>I tried mucking with it but didn't have much luck it keeps adding to the width when it's opened an closed. Also because the compose icon is in a position: fixed</span>
      </div>
    </div>
    <div class="brd" role="list" jscontroller="tnECjd">
      <span class="bzB"> Attachments</span>
      <div class="brc" data-index="0" tabindex="0" title="image.png" role="listitem" jsaction="lkS8Jd"><img class="brf" aria-hidden="true" src="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x16.png" srcset="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x32.png 2x"><span class="brg">image.png</span></div>
      <div class="brc" data-index="1" tabindex="0" title="image.png" role="listitem" jsaction="lkS8Jd"><img class="brf" aria-hidden="true" src="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x16.png" srcset="//ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_image_x32.png 2x"><span class="brg">image.png</span></div>
    </div>
  </td>
  <td class="byZ xY"></td>
  <td class="yf xY "><img class="yE" src="images/cleardot.gif" title="Has attachment" alt="Has attachment"></td>
  <td class="xW xY "><span title="Mon, Apr 8, 2019, 5:44 PM" id=":2d" aria-label="Mon, Apr 8, 2019, 5:44 PM"><span>Apr 8</span></span></td>
  <td class="bq4 xY">
    <ul class="bqY" id=":2e" role="toolbar">
      <li class="bqX brq" data-tooltip="Archive" jsaction="JqEhuc" jscontroller="pk1i4d"></li>
      <li class="bqX bru" data-tooltip="Delete" jsaction="zM6fo" jscontroller="pmCKac"></li>
      <li class="bqX brs" data-tooltip="Mark as unread" jsaction="XdlY1e" jscontroller="VtSflc"></li>
      <li class="bqX brv" data-tooltip="Snooze" jsaction="u4Fnue" jscontroller="PKSrle"></li>
    </ul>
  </td>
</tr>
```

**Comment by boukestam** [comment]
So the issue was indeed with the important indicators. I've modified your code a bit so it now works in both cases. Also I've made the reminder icons work the same way as the avatars. Hopefully this fixes all issues

**Comment by russelldc** [comment]
@boukestam Nice! I found an issue:

If you have Keyboard shortcuts turned on (Settings -> General -> Keyboard shortcuts on), this highlights the currently 'selected' email, so you know which is in focus when navigating with arrow keys.

With your most recent change, the highlight was moved to the right.

Screen Shot 2019-04-10 at 5 36 16 PM

**Comment by boukestam** [comment]
Thanks! I would have never found that issue. It should be fixed now

**Comment by russelldc** [comment]
Great, looks fixed on my end.

Just one more bug... :P I love that the reminder icons are back now, but they're not hiding on hover or checked.

**Comment by boukestam** [comment]
Wow, thanks again :) Fixed that one as well. I'll merge it with the master branch on which I just committed some code which fixes some firefox issues. Then I'll release it on firefox add-ons and inform the person who wrote an issue about the missing firefox extension

**Pull request merged**
