### PR TITLE
[#70] Prevent bundled emails from flashing/appearing in inbox

### PR DESCRIPTION
**Pull request by russelldc**
@abasiri I implemented the fix for bundled email flashing that you described (No. 3 in issue #70)

Let me know if this is what you had in mind, seems to work for me.

### CODE REVIEW

**Comment by abasiri** [comment]
Thanks for working on this, i'll take a look this evening.

**Comment by russelldc** [comment]
@boukestam If you get a chance, could you test this one (I notice you just tested and merged the other related PR)

If you're not familiar, this is supposed to stop hidden bundled emails from briefly re-appearing in the inbox when returning from a bundle to the inbox, or when the inbox list redraws/polls for whatever reason.

Here's a GIF on master branch (without this fix) of the problem. You'll see when I return to the inbox, the email from you (Bouke) flashes underneath the bundle.

ezgif-3-2f83d8041386

**Comment by boukestam** [comment]
I don't really see anything going wrong. I don't see what it is supposed to fix either, but I guess that is exactly the point of this :)

**Comment by russelldc** [comment]
@boukestam I added a gif of what it was supposed to fix :P But either way, it works!

**Pull request merged**
