### PR TITLE
[#60, #64] Change favicon to Inbox & Hide inline ads/promotions

### PR DESCRIPTION
**Pull request by russelldc**
The ads show up at the top of Social and Promotions if you have the Primary/Social/Promotions/Forum tabs enabled.

The favicon is a base64 data uri. This can later be changed to point to the extension's image folder, whenever we decide to fix that for all the other icons.

### CODE REVIEW

**Comment by russelldc** [comment]
Added new commit with favicon for issue #60

**Comment by russelldc** [comment]
Added new commit removing the drag icon for issue #64

**Comment by russelldc** [comment]
I updated the font family, size, weight and opacity of the first letter avatar icons to exactly match Inbox.

f08504bce7c2f83e208e21d253dc2a6e

**Comment by russelldc** [comment]
The latest change, including the Roboto Medium font as a file, shows how easy it should be to locally load the action/button icons and any other images we've been hosting elsewhere.

**Comment by boukestam** [comment]
Sorry for my late reply, I had a busy time at work. This change was actually something I thought about too. Awesome that you already did it!

**Pull request merged**
