### PR TITLE
centralize tabs

### PR DESCRIPTION
**Pull request by guybbb**

### CODE REVIEW

**Comment by russelldc** [comment]
For anyone else wondering exactly what this change does, since @guybbb didn't add a description:

1. The description for the Chrome/Firefox extensions recommends users to turn off this feature, but if you do still use the Gmail tabs that algorithmically break up your inbox into Primary / Promotions / Social, etc. then those tabs will now now center-aligned and a similar width as the email list below.
1. The change that hid the unread counters on the left menu was rolled back. Unfortunately this just turns them back on, it doesn't fix their broken behavior.

@guybbb Turning off the label counters recently was deliberate for 2 reasons:
1. They weren't present in Inbox, and some users of the extension were complaining.
1. More importantly, the counts for the Inbox folder are not updating when changes are made. The user has to refresh to force the count to update.

Here's a before/after gif:
ezgif com-optimize (1)

**Comment by guybbb** [comment]
hi @russelldc! sorry for not adding a description

you are correct regarding the label, probably would make sense to keep them off

I've updated the PR

**Comment by russelldc** [comment]
@guybbb 

👍 No problem. Could you undo the spacing changes? It seems you added 8 spaces before and 1 space after that .bsU line.

Also, this doesn't have to do with your PR specifically, but keep in mind that I noticed once in a while that my non-Primary emails would sometimes load into the Primary tab. Not sure what causes it to happen intermittently.

**Comment by guybbb** [comment]
You are right, I've noticed the same behavior but I don't think it is related to the PR
I'll try to investigate a little bit later and see if it can be fixed

**Comment by russelldc** [comment]
@guybbb What do you think about horizontally centering the title & icon within the tabs as well?

This worked for me:

```css
.J-KU-Jg-K9.aAA > .aRz > .aAy {
  justify-content: center;
}

.aAy > .aKp {
  margin-left: 0;
}
```

Screen Shot 2019-04-24 at 1 33 20 PM
Screen Shot 2019-04-24 at 1 33 43 PM

**Comment by guybbb** [comment]
@russelldc I don't know if it worth the risk of later maintaining this design

The CSS selector approach is quite flaky since google can change these classes at any given moment

**Comment by russelldc** [comment]
@guybbb Ha, but if you're worried about that, the entire extension goes out the window.

I mean, take a look at style.css! 😛 Actually, your initial work here is similar as well.

**Comment by guybbb** [comment]
@russelldc of course :smirk: 
I have tried to minimize the changes to centralize the tabs so they won't feel out of place
anyway to me both work well

Do you want me to add these change to the PR?

**Comment by russelldc** [comment]
@guybbb Please go ahead and add it, unless you think it's not an improvement. To me, I always thought they looked a little weird left-aligned, but I might be odd.

**Comment by guybbb** [comment]
@russelldc it does look better, I have pushed the changes

**Pull request merged**
