### PR TITLE
Updated some more features

### PR DESCRIPTION
**Pull request by joeytroy**
More fixes and bug changes.

### CODE REVIEW

**Comment by russelldc** [comment]
I rebased on latest master and pushed

**Comment by russelldc** [comment]
@boukestam Specific changes:

- [#35] Hide red number/count on left menu (they weren't there in Inbox, but also because they don't seem to update when changes are made)
- [#13] Increase z-index of Compose and Reminder such that they show above the right-side task bar when one of the complementary Google apps are open
- [#20] Sun background image will no longer appear at the bottom of Search pages
- [#41] Contacts which don't start with A-Z (ex, numbers or symbols) will now get an avatar name icon (white text on black circle)
- Add Firefox Add-on link to Github README
- Updated screenshot in README
- I noticed every other commit between us was using different spacing in style.css. I've now made it consistent to the most common spacing that was in the file at the time: Tab with size of 2 spaces
- [#15] Display Label colors in left menu
- [#49] Fixes width of email to be the same as that of the email list, and does the same for the toolbar above emails as well.
- [#50] Small rectangular grey area covering parts of the side bar title

**Comment by gnowland** [comment]
@russelldc these Firefox "fixes", though now only targeted at Firefox, are still causing undesirable effects in Firefox (see screenshot).
Mac Mojave 10.14.3 Firefox version 66.0.3 (64-bit).

Screen Shot 2019-04-11 at 10 59 00 AM

What bug are they trying to solve? When I remove these styles everything looks perfect in my inbox... If I know what to look for I'll try and PR a fix.

Cheers!

**Comment by russelldc** [comment]
@gnowland That's a question for @boukestam .

I have no clue what his changes were supposed to solve. Just as you're seeing, when I loaded @boukestam 's original commit with these Firefox-related changes into Firefox, I was seeing weird issues. When I commented those changes out, I had no issues at all.

I'm really confused about all this, especially because the version of the extension that was published to the Firefox Add-ons store didn't cause those same issues, as when I loaded the extension code manually. I'm hoping he can shed more light.

**Comment by russelldc** [comment]
@gnowland This PR doesn't actually touch anything related to those Firefox changes, by the way.

It's listed as one of the commits, but if you look at the actual 'Files changed' diff, there's nothing new compared to the boukestam/inbox-in-gmail master branch.

**Comment by gnowland** [comment]
@russelldc yep I see that was changed after the rebase. :)

**Pull request merged**
