### PR TITLE
Gmail Update

### PR DESCRIPTION
**Pull request by joeytroy**
Added new features, colors fixes and revamped code.

### CODE REVIEW

**Comment by boukestam** [comment]
I'm seeing this: 
image

Is this correct? By looking at the code it looks like it should be inbox, snoozed, done.
How does it look at your end?

**Comment by russelldc** [comment]
### Edit: This was resolved in later commits.

Bug: The Compose floating action button disappears when the left menu is hidden.

**Comment by russelldc** [comment]
> Is this correct? By looking at the code it looks like it should be inbox, snoozed, done.
> How does it look at your end?

For me, it's called "All Mail" instead of "Done" as well, although I've dragged it up out of the More section.

**Comment by russelldc** [comment]
### Edit: This was resolved in later commits.

Style issue: The current Gmail left menu, as well as the real Inbox's left menu, animate left-right when being displayed, rather than suddenly appearing.

This works well, essentially the same css used on Inbox now, but with just this, the Compose FAB 
shows up inside the left menu.

```css
/* Left sidebar */
div.aeN {
  transform: translateX(0);
}

/* Left sidebar collapsed */
div.aeN.bhZ {
  transform: translateX(-242px);
  transition: transform .15s ease-in-out;
}
```

**Comment by russelldc** [comment]
@boukestam I'd recommend taking another look at this, since the recent commits.

**Comment by boukestam** [comment]
Thansk guys, I'm testing right now
I have found a small styling issue with the box shadow being cut off

image

Also in the left sidebar it's still Inbox, Starred, Snoozed. I thought the reorder code was supposed to make it Inbox, Done, Snoozed? Maybe I just don't understand it correctly, but looking at the code that is what is looks like. Also All Mail is not being renamed to Done, which it also looks like it should do.
Is this right?

**Comment by russelldc** [comment]
@boukestam I don't think it should be called Done, because All Mail contains ... all mail 😄both archived and unarchived. But I agree, if it's possible, it should be moved up next to Inbox and Snoozed.

@g60madman let me know if you're working on that already, or if I should.

**Comment by joeytroy** [comment]
These new commits should fix this issue.

**Comment by russelldc** [comment]
To actually turn All Mail into Done, we could point it to 'in:archived'.

**Comment by russelldc** [comment]
Oh, I see, @g60madman your code attempts to add a link to a search for #search/-is%3Ainbox, which is similar to /#archive

Do you know why that code's not working?

Edit: Oh, it starts with the function initMenu, but that function is never called.

**Comment by russelldc** [comment]
I made some progress on 'Done'. It's not renamed to Done yet, but it goes to /#archive. Also, it moves up next to Inbox and Snoozed... but only if you click the More/Less button in the inbox/folder list.

**Comment by russelldc** [comment]
Okay, now the text on the link says 'Done', but like mentioned before, only after clicking the More/Less button.

This change for some reason seems to break the Trash and Spam links. They're still there, but clicking them does nothing. Investigating now...

**Comment by russelldc** [comment]
Alright, I figured out why the More button had to be clicked for anything to update:

The code making this change waits to find all of the menu nodes. If they're hidden in More, it can't proceed, because it would encounter errors trying to attach events to an element/node that doesn't exist. 

My simple 'fix' has one problem: When clicking away from Done, it will only be un-highlighted if you click on Inbox or Snoozed. If you're looking at Done, and switch to a different folder that's not Inbox/Snoozed, it will stay highlighted along with the new one you've clicked.

Screen Shot 2019-04-05 at 2 49 39 AM

Edit:
In fact, here's another issue:

If the user hasn't already dragged Done up into their upper favorite(?) subsection of inbox folders, this code won't activate until they click More.

Maybe the code could programmatically click More to solve all this.

**Comment by russelldc** [comment]
And... fixed! Please check this out and test it @boukestam @g60madman

**Comment by boukestam** [comment]
Looks good! The sidebar is now almost exactly like inbox. I've tested it a bit and found no more problems. If you guys can also test a bit, then if you agree I will publish a new version to the store and merge with the main repository. Btw, the extension is doing great:
Capture
We are also getting a lot of feedback which it amazing to read

**Comment by russelldc** [comment]
Awesome :) I haven't encountered any issues so far. The only thing I'd want to change is: Right now, if the user didn't have All Mail dragged into the top area already, there will be another All Mail in the More section, in addition to the Done up top. The one below correctly points to /#all, the only issue is that the icon is the Done checkmark.

I'm not sure this issue is important important enough to delay release, but up to you!

As of today, I am automatically redirected away from Inbox for all my accounts 😢

**Comment by boukestam** [comment]
If that is a simple fix then I can wait for that. It could annoy a few people who have expanded the more section. If it is more difficult than I will just publish since the sidebar is overall much better I think, even with that issue.

**Comment by russelldc** [comment]
@boukestam Fixed the Done/All Mail icon problem.

**Comment by joeytroy** [comment]
@boukestam I say push it up! Also might be helpful to list the new github and maybe list the developers as well ;)

**Comment by russelldc** [comment]
@g60madman I just set the homepage link to this repo in the manifest.json. That's where you go when you right click the extension and click the first option, 'Inbox in Gmail'.

@boukestam should add it as the homepage on the Chrome Web Store as well

**Comment by joeytroy** [comment]
@russeldc Nicely done!

**Comment by joeytroy** [comment]
I found a small issue. When you star an email all the way to red star it shows this

image

**Comment by joeytroy** [comment]
I got the red button fixed but it's showing the stupid red box  on top of it

/* Red stared with redband */
td.apU.xY .T-KT.xg::before {
	background-image: url('https://i.ibb.co/pvycvpK/ic-mark-red-bang-clr-24dp-r4-2x.png') !important;
	background-size: 24px !important;
}

image

**Comment by russelldc** [comment]
@g60madman I don't use stars, how would I get that to show to test this?

**Comment by joeytroy** [comment]
@russelldc you will need to just check mark an email it will go blue, if you check mark it again it will show red.

**Comment by joeytroy** [comment]
I am going to work on pulling all the images down and host them external. I am worried Google may kill the links eventually to the static images.

**Comment by russelldc** [comment]
@g60madman Why another random image host, and not just in the icons folder of the extension?

**Comment by boukestam** [comment]
We can actually store the images in an images folder in the extension root. Then we can refer to those images with chrome.runtime.getURL

**Comment by russelldc** [comment]
@boukestam Nice job responding the same exact time as me, but nothing can stop @g60madman  :P

**Comment by joeytroy** [comment]
Fail...I will work on moving them into the folder
image

**Comment by joeytroy** [comment]
OK I am failing on getting the images to pull from the local folder. Can some one take care of that. Here is the images. 
[images.zip](https://github.com/boukestam/inbox-in-gmail/files/3048671/images.zip)

**Comment by russelldc** [comment]
I want to get that favicon api request integrated asap... after I added the styling to hide checkboxes when not checked or hovering, the emails look so sad and plain.

**Comment by joeytroy** [comment]
I found this link to fix the images to load locally, but still can't figure it out

https://stackoverflow.com/a/32130426

**Comment by russelldc** [comment]
We could use the Base64 method, considering these are pretty small, simple images.

For example, here's the Pin icon:

```
url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAVUlEQVR4Ae3WsRHAIAxDUY3KZhqNUUiZCl+KyJcc/7vXK2gQER3Rqu8HgMt5S0nC6XcQAAAAQBMwNLfA1MiNv4Ksh/ddYAfGAgAAaAB8fxhzhEXU3AXHwUDMUEVsEgAAAABJRU5ErkJggg==')
```

A little unwieldy... I'll look into fetching from the images folder when I get back to my desk later.

**Comment by russelldc** [comment]
Oh right, nice job remembering to bring over the empty inbox Sun 👍 
There's a very thin line of blue at the bottom of it, though.

And about changing the title on the header to Inbox, I really want to programmatically change that depending on the inbox folder you're in, see: Issue #10

**Comment by joeytroy** [comment]
@russelldc  Check out this commit

https://github.com/kallepersson/inboxtheme/commit/d649cf7c7aa61da1a219e63e64318b227e262422

There is some java that goes along with it to to change the tool bar color when switching between, snoozed, done, inbox etc.

https://github.com/kallepersson/inboxtheme/blob/master/src/menu.js#L28-L49

**Comment by joeytroy** [comment]
@russelldc here is the plugin source code. I already ran the sh script they have so you can just load it and see they have the top bar working properly based on switching from section to section i.e. inbox, sent, etc.

[inboxtheme-master.zip](https://github.com/boukestam/inbox-in-gmail/files/3049001/inboxtheme-master.zip)

**Comment by russelldc** [comment]
@g60madman Hmm.. as far as I know, that code is what switches the highlight on the left menu. And it's in our project already. I think you had added it a while back, but didn't set it to initiate, until my work earlier up in this comment chain that fixed the Done folder.

**Comment by joeytroy** [comment]
@russelldc got ya, well they have code to switch the top bar and also the title in their code

image
image
image

**Comment by joeytroy** [comment]
@russelldc here is the working one

[inboxtheme-master.zip](https://github.com/boukestam/inbox-in-gmail/files/3049039/inboxtheme-master.zip)

**Comment by russelldc** [comment]
No need to compile and post that, we can just look at the source code. I'd get this done now, but I've gotta jet to an event.

Looks like this css is relevant (Edit: oh, I missed that you linked to this too):
```
/* Toolbar background */
._in header { background-color: #898984 !important; }
._in[data-hash*="#inbox"] header { background-color: #4285f4 !important; }
._in[data-hash*="#starred"] header { background-color: #FDB500 !important; }
._in[data-hash*="#snoozed"] header { background-color: #ef6c00 !important; }
._in[data-hash*="#archive"] header { background-color: #0f9d58 !important; }
```
(I changed the #search/is-inbox to #archive)

They work with the _in element/class in this file:

https://github.com/kallepersson/inboxtheme/blob/master/in.js

**Comment by russelldc** [comment]
Keep in mind, if we're adapting this code, as per the MIT license, @boukestam needs to add a LICENSE file to this repo as well.

**Comment by joeytroy** [comment]
@boukestam @russelldc I already pulled some of their code so we need to add the MIT license.

**Comment by joeytroy** [comment]
@russelldc  here are more icons I added for all the pin colors

[images.zip](https://github.com/boukestam/inbox-in-gmail/files/3050035/images.zip)

**Comment by joeytroy** [comment]
@russelldc any luck getting the colors to change when clicking on ingox, snoozed, etc? It's still open on the https://github.com/boukestam/inbox-in-gmail/issues/10

**Comment by russelldc** [comment]
@g60madman No, but I'm pretty sure I know how to get it done. I've been sick the past 2 days, unfortunately. I might be able to tomorrow.

**Comment by joeytroy** [comment]
@russelldc unplug brother and rest. Like Hogan says

image

**Pull request merged**
