### PR TITLE
[#64] Center the checkbox with the avatar.

### PR DESCRIPTION
**Pull request by abasiri**
This addresses #64 by centering checkbox with avatar.

image

### CODE REVIEW

**Comment by russelldc** [comment]
@abasiri I'd recommend checking out the lasted inbox-in-gmail/inbox-in-gmail master branch.

I'd fixed this already, at the same time that I fixed the spacing of the avatar and subject to match the original Inbox look.

That's awaiting merge in PR #56 

Although, your change hides the drag icon, which I agree should probably be done. In fact, I'll go adopt that change into my PR (which is really just inbox-in-gmail/inbox-in-gmail@master). **Edit**: done

I don't have the "Important" icons turned on in settings, I'd forgotten that existed in Gmail. So my change might look slightly odd if you have those on, let me know your opinion, please.

**Comment by russelldc** [comment]
I noticed you changed the font-weight from 300 to 400.

After looking through more example screenshots of Inbox, old and new, it seems like that's probably more accurate, although you need to lessen the opacity of the character inside the avatar circle, if you want to really match it. See these Inbox screenshots for reference:

Screen Shot 2019-04-27 at 3 14 56 PM
Screen Shot 2019-04-27 at 3 17 04 PM
Screen Shot 2019-04-27 at 3 16 30 PM

However, if you change the font-weight, you also need to change the vertical alignment of the character within the circle. Check out this GIF I made of pre and post font-weight change:

ezgif-3-620f0089ab61

**Comment by russelldc** [comment]
Alright, about the font-weight issue: After admittedly obsessing over it, comparing to screenshots from this blog post:
https://www.dantilden.com/2019/03/20/google-inbox

I've realized a few things:

1. The font-size should be increased from 13px to 16px.
2. At this increased font-size, it pops back down vertically, to how it was originally at 300. font-weight doesn't seem to affect the vertical placement anymore.
3. I think this opacity comes closest: `.avatar { color: rgba(255, 255, 255, 0.65); }`
4. These letter avatars were using a different font. I've attached a screenshot of my changes listed above (left) versus real Inbox (right):

Screen Shot 2019-04-27 at 6 09 13 PM

It's not Helvetica Neue or Product Sans, trying to figure it out.

Update: Found it ... or at least something super close. 

Roboto with font-weight 500, font-size 18px.
Here's a comparison GIF, committing this now to inbox-in-gmail/inbox-in-gmail@master.

f08504bce7c2f83e208e21d253dc2a6e

**Comment by abasiri** [comment]
Nice, that looks very close. Mainly, if it's centered with the checkbox, it's good enough for me :)

Should I add that in my PR, or is that already in your PR?

**Comment by russelldc** [comment]
It's already added to my PR, #56 

That fork/PR also has the checkbox centered with the avatar. See this screenshot:

Edit: added ruler
Screen Shot 2019-04-29 at 5 54 56 PM

**Comment by boukestam** [comment]
Thanks a lot!

**Pull request merged**
