### PR TITLE
Add calendar action attachment + update attachment styles

### PR DESCRIPTION
**Pull request by abasiri**
I'll follow with RSVP cards and bundles once this is merged down.

### CODE REVIEW

**Comment by abasiri** [comment]
attachments will now look like this:
image

**Comment by abasiri** [comment]
Here is what calendar invitations now look like:

image

**Comment by russelldc** [comment]
I don't have time for a full review on this at the moment, but I noticed that with your version, I'm getting a much larger padding or margin on the top of my inbox email list.
Screen Shot 2019-04-07 at 1 36 01 AM

**Comment by abasiri** [comment]
Thanks for taking a look. That's weird. I'm not getting any padding at the top. I'll see if I can repro it.

image

**Comment by abasiri** [comment]
@russelldc Unfortunately I wasn't able to repro the issue with the padding. If you get a chance to look at it with the developer tools that would really help.

**Comment by abasiri** [comment]
I think I figured out the issue, added a fix.

**Comment by boukestam** [comment]
Thanks a lot for your help! The calendar invites and attachments look great. I see you have changed a lot of other parts of the code so it is a bit hard to see what exactly you changed and why. Can you explain a bit about the changes you made in the code?

**Comment by russelldc** [comment]
Agreed with @boukestam.

I can confirm the latest change did fix the large top spacing issue I reported earlier.

**Comment by abasiri** [comment]
@boukestam I'm happy to walk through it. The primary change is readability of the method `updateReminders`. So if you start reading there, the rest should be easier to follow. The main concept of the change is to use updateReminders method as a main loop that identifies email types and acts on them. To that end, it should probably be renamed to something like 'processEmails'.

The structure of the main loop in updateReminders is to have tester methods for different email types, and then take action. So for example there is a `isReminder` method that checks if the current email is of type reminder. The next one is `isCalendarEvent`. And lastly it's processing the Date labels such as Today and Yesterday.  I have another change locally that also adds `isSnoozed`. As snoozed emails will currently break the date labels. If it's helpful, i'm happy to annotate the PR with comments to point to different sections.

**Comment by boukestam** [comment]
I have looked at the code and I think it's definitely an improvement in readability. I also tested it and couldn't find any bugs. Thanks a lot for your help! I will also publish a new version today to roll out your changes

**Comment by russelldc** [comment]
@abasiri Actually, sorry I misspoke. The new commit did not fix the top padding/spacing issue. It went away because I switched from the 'Starred First' inbox type to the 'Default' inbox type.

With the latest code, and the 'Starred First' inbox type, that large space is still present.

**Pull request merged**
